version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "8013:3001"
    network_mode: bridge
    volumes:
      - .:/app
      - /app/node_modules
    container_name: facialme_website
